### ISSUE TITLE
RebuildStaticCacheTask loads pages in Draft mode

### ISSUE THREAD

**Issue by adamjudd** [silverstripe-labs/silverstripe-staticpublisher#42]
In instances where multiple pages are cached, I'm seeing the cache being done on the draft version of the page.

I've set up my template to output the current stage to the page. If I publish a top-level page within the admin, it shows correctly as `Stage.Live`. If I cache a child page though, the child page is cached as `Stage.Live`, the parent page displays as `Stage.Stage`. Consequently, that page will show live and draft content.

I've tried forcing the `?stage=Live` URL param onto the URL before caching within staticpublisher, but that doesn't change anything. Instead I altered the FilesytemPublisher `PublishPages()` function to temporary change the stage and that seemed to fix it.

I'm happy to submit a pull request with this change, but wanted to check if I'm missing something first.

**Comment by NobrainerWeb** [comment]
Would you mind sharing your code on this issue? I have the sameproblem i think.
When i run RebuildStaticCacheTask, all pages including drafts are added (and included in the menu)

**Comment by adamjudd** [comment]
@NobrainerWeb - sure thing. So in code/extensions/FilesystemPublisher.php, edit `publishPages()` like this:

```php
	public function publishPages($urls) { 
		$oldStage = Versioned::current_stage(); // save current mode
		Versioned::reading_stage("Live"); // temporarily overwrite mode
		
		...
		
		Versioned::reading_stage($oldStage);

		return $result;
	}
```

So that would the the two lines at the start, and then the `Versioned::reading_stage()` call at the end of the function. Everything else stays the same. I think that's all you need to do.

**Comment by NobrainerWeb** [comment]
Thx for sharing :+1: 
That is also what i ended up doing.

**Comment by wernerkrauss** [comment]
@adamjudd this sounds like a serious bug to me, would you mind creating a PR for this issue?
