### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by ss23** [silverstripe-labs/silverstripe-staticpublisher#53]
As raised by @dhensby in #34 we need to tag a new release at some point.

@candidasa Any thoughts on just tagging a new v2.0.0?

**Comment by tractorcow** [comment]
This isn't a supported module, so, feel free to do what you want.

**Comment by ss23** [comment]
Yep, that's why I'm asking for advice rather than following a procedure, @tractorcow 
I'd still like our "un-supported" modules to be tagged properly and usable...

**Comment by dhensby** [comment]
1.1.0 tagged
